### ISSUE TITLE
page access from front

### ISSUE THREAD

**Issue by JannIds** [dgvirtual/bonfire2-pages-module#1]
How to access pages from frontpage. I assume we need to meak custom routes based on slugs?

**Comment by dgvirtual** [comment]
Yes; I created only the admin module, the public  display implementation was beyond my objective. 

So, routes for public display, as well as the whole implementation is up to the creator of a website.

**Comment by stitpragya22** [comment]
thanks for this, i just also create route in public like this in Pages Module's Routes.php
// public routes no filtering or but group by name space
$routes->group('', ['namespace' => 'App\Modules\Pages\Controllers'], static function ($routes) {
    $routes->get('page/(:segment)', 'PagesController::show/$1', ['as' => 'page-show']);
});

**but how to add the layout properly from App/master.php or custom layout ?**

but when I use as following, it gives me admin's master layout 
I just try to find docs but unable to find how to add custom layout or how correctly apply specific layout, I think in themes fer we have 
Admin
App
Auth
and each one have the master.php so to apply specific one how to mention it in page

// following gives me same as admin layout
<?= $this->extend('master') ?>

<?php 
$viewMeta->setTitle(esc($page->title));
$viewMeta->addMeta(['title' => esc($page->title)]);
$viewMeta->addMeta(['description' => esc($page->excerpt)]);
?>

<?= $this->section('main') ?>

**Comment by dgvirtual** [comment]
Hi, the code of this module is concerned only with the admin area aspect. And the App theme of Bonfire2 is rudimentary.

However, I have a separate project where I have a full-blown frontpage example with a Bootstrap-based App theme: 

https://github.com/dgvirtual/bonfire2-frontpage-theme

 I do not have controller/views for display of Pages there, but it is pretty basic to add. The main thing is to have a base AppController that every controller for the front-facing pages should extend, this is [the particular example](https://github.com/dgvirtual/bonfire2-frontpage-theme/blob/main/app/Modules/Bonfire2Home/Controllers/AppController.php). It should include after the class declaration: 

```php

    use Themeable;

    protected $theme = 'App';

```

Of course the Themeable should be imported with use statement at the top of the class file. 

Tell me if you figure it out.
