### ISSUE TITLE
You do not have the correct permissions.

### ISSUE THREAD

**Issue by nanangsb** [dgvirtual/bonfire2-pages-module#3]
- Instalation as instructions
- super admin permission group checked for page
Still dont have correct permissions

**Comment by dgvirtual** [comment]
Could you elaborate: do you mean you can login, access admin panel, but do not see the module "Pages" in the menu, and cannot manage pages on admin panel?

**Comment by nanangsb** [comment]
I can login , And I can also see the page menu and in the dashboard. When I click, a notification appears "You do not have the correct permissions". 
In the "group permissions" menu, I have checked everything for the page module. 
![Screenshot_2024-02-07-17-57-22-413-edit_com android chrome](https://github.com/dgvirtual/bonfire2-pages-module/assets/8703377/ba196525-5aa2-4954-8145-8c0250ca7fd7)
![Screenshot_2024-02-07-17-56-07-162-edit_com android chrome](https://github.com/dgvirtual/bonfire2-pages-module/assets/8703377/6f8b0f01-3394-4791-b21a-68280037f8ae)

**Comment by dgvirtual** [comment]
Well, I did not have much time to investigate, but it seems you get stuck on this line: https://github.com/dgvirtual/bonfire2-pages-module/blob/30425a680b24ae1221550998a444a85be7145e2c/Pages/Controllers/PagesController.php#L41

But that only tells us the same - the permissions do not get applied correctly. 

By the way, did you start with a fresh Bonfire2 install, or added my module to an existing install of Bonfire? And did you doublecheck the install procedure?

**Comment by nanangsb** [comment]
Yes, its fixed by adding `'pages.list'        => 'View page list',` on `app/Config/AuthGroups.php` . 
Its missing on documentation

**Comment by dgvirtual** [comment]
> Yes, its fixed by adding `'pages.list' => 'View page list',` on `app/Config/AuthGroups.php` . Its missing on documentation

Oh my, funny that its only now that someone took time to report it. Thank you! I updated the Readme file.
